name: Sports Prop Logger

on:
  schedule:
    # SCHEDULE EXPLANATION (UTC Time):
    # We use UTC because GitHub servers are in London/UTC time.
    # Assuming EST (UTC-5):
    #
    # --- SLOW MODE (Every 4 Hours) ---
    # 05:00 UTC = 12:00 AM EST
    # 09:00 UTC = 04:00 AM EST
    # 13:00 UTC = 08:00 AM EST
    # 17:00 UTC = 12:00 PM EST
    # 21:00 UTC = 04:00 PM EST
    #
    # --- FAST MODE (Every 1 Hour for "Steam") ---
    # 22:00 UTC = 05:00 PM EST
    # 23:00 UTC = 06:00 PM EST
    # 00:00 UTC = 07:00 PM EST
    # 01:00 UTC = 08:00 PM EST
    # 02:00 UTC = 09:00 PM EST
    # 03:00 UTC = 10:00 PM EST
    # 04:00 UTC = 11:00 PM EST
    
    - cron: '0 5,9,13,17,21,22,23,0,1,2,3,4 * * *'

  workflow_dispatch: # Allows you to force-run it manually via the "Actions" tab

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # CRITICAL: Allows the bot to save the CSV file to your repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pandas

      - name: Run Scraper
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: python main.py

      - name: Commit and Push Data
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add prop_log.csv
          # The line below saves the file. If no lines changed, it skips quietly.
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update prop log" && git push)
